### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by STOKYS** [STOKYS/JavaScriptGame#1]
### Ideas:
> - In multiplayer boss healthbar
> - Bot update every shot and kill, but the first target is set to be enemy[0]

**Comment by SeezoCode** [comment]
That idea is a great idea

**Comment by STOKYS** [comment]
That was not an idea but bug fixSent from my Samsung Galaxy smartphone.
-------- Original message --------From: SeezoCode <notifications@github.com> Date: 9/22/20  13:09  (GMT+01:00) To: STOKYS/JavaScriptGame <JavaScriptGame@noreply.github.com> Cc: STOKYS <dejv2004S@gmail.com>, Author <author@noreply.github.com> Subject: Re: [STOKYS/JavaScriptGame] Ideas (#1) 
That idea sucks, make multiplayer
